Neos:
  Form:
    presets:
      default:
        formElementTypes:
          'Wwwision.Form.MultiColumnSection:TwoColumns':
            superTypes:
              'Neos.Form:FormElement': true
            implementationClassName: Wwwision\Form\MultiColumnSection\Form\TwoColumnFormElement
            renderingOptions:
              renderableNameInTemplate: container
            properties:
              elementClassAttribute: row
  Neos:
    fusion:
      autoInclude:
        Wwwision.Form.MultiColumnSection: true
