Neos:
  Form:
    presets:
      default:
        formElementTypes:
          'Wwwision.Form.MultiColumnSection:TwoColumns':
            superTypes:
              'Neos.Form:FormElement': TRUE
            implementationClassName: 'Wwwision\Form\MultiColumnSection\Form\TwoColumnFormElement'
            renderingOptions:
              renderableNameInTemplate: container

  Neos:
    fusion:
      autoInclude:
        'Wwwision.Form.MultiColumnSection': TRUE
